# Generated by Django 5.1.4 on 2024-12-13 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCatering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPhotography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStageDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Style', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catring/')),
                ('description', models.TextField(max_length=200)),
                ('pricePerGuest', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photography/')),
                ('description', models.TextField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StageDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stagedecor/')),
                ('description', models.TextField(max_length=400)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('location', models.CharField(max_length=80)),
                ('capacity', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('availability', models.BooleanField(default=True, help_text='1 - Available, 0 - Not Available')),
            ],
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.AddField(
            model_name='bookingcatering',
            name='catering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cateringbookings', to='Events.catering'),
        ),
        migrations.AddField(
            model_name='bookingphotography',
            name='photography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography', to='Events.photography'),
        ),
        migrations.AddField(
            model_name='bookingstagedecor',
            name='stageDecor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagedecoration', to='Events.stagedecoration'),
        ),
        migrations.AddField(
            model_name='bookingvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Events.venue'),
        ),
    ]
