# Generated by Django 5.1.4 on 2024-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_bookingcatering_bookingphotography_bookingstagedecor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
