# Generated by Django 5.1.4 on 2024-12-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_img', models.ImageField(upload_to='')),
                ('catering_img', models.ImageField(upload_to='')),
                ('stage_img', models.ImageField(upload_to='')),
                ('Photography_img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('services', models.TextField(help_text='Enter services separated by commas.')),
            ],
        ),
    ]
