# Generated by Django 5.1.4 on 2024-12-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_weddingpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingpackage',
            name='Photography_img',
            field=models.ImageField(upload_to='wedding_package'),
        ),
        migrations.AlterField(
            model_name='weddingpackage',
            name='catering_img',
            field=models.ImageField(upload_to='wedding_package'),
        ),
        migrations.AlterField(
            model_name='weddingpackage',
            name='stage_img',
            field=models.ImageField(upload_to='wedding_package'),
        ),
        migrations.AlterField(
            model_name='weddingpackage',
            name='venue_img',
            field=models.ImageField(upload_to='wedding_package'),
        ),
    ]
