# Generated by Django 5.1.4 on 2024-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_alter_weddingpackage_photography_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingpackage',
            name='services',
            field=models.TextField(help_text='Enter services separated by commas,'),
        ),
    ]
